[package]
name = "glium_generics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "glium_generics"
path = "src/lib.rs"
test = true
crate-type = ["lib"]

[dependencies]
glium = "0.34.0"